services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - '5005:5005'
    depends_on:
      - burty_postgres
      - burty_minio
      - burty_redis
    restart: unless-stopped
    environment:
      STARTUP_COMMAND: ${STARTUP_COMMAND}
    command: >
      sh -c "${STARTUP_COMMAND}"

  burty_postgres:
    image: postgres:latest
    container_name: burty_postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'jit=off']
    ports:
      - '5432:5432'
    restart: unless-stopped

  burty_minio:
    image: minio/minio:latest
    container_name: burty_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data
    restart: unless-stopped

  burty_redis:
    image: redis:latest
    container_name: burty_redis
    ports:
      - '6379:6379'
    restart: unless-stopped

volumes:
  pg_data:
  minio_data:
